version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.Api
    ports:
      - "8050:80"
  client:
    build:
      context: .
      dockerfile: Dockerfile.Client
    ports:
      - "8060:80"
    depends_on:
      - api
